[build]
publish = "dist"
command = "npm run build"
branch = "refs/heads/main"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 20
  
[build.environment]
NODE_VERSION = "20"


